services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports: 
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - database_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand('ping').ok\" | grep 1"]

  server:
    build:
     context: ./server_ichgram
    container_name: server_ichgram
    env_file:
      - ./server_ichgram/.docker.env
    ports:
      - 3333:3333
    depends_on:
     mongo:
       condition: service_healthy

  client:
    build:
      context: ./client_ichgram
    container_name: client_ichgram
    ports:
      - "3000:80"

volumes:
  database_data: 